os:
  - linux
  - osx
  - windows

osx_image: xcode11.3
dist: bionic
language: node_js

env:
  global:
    - YARN_GPG="no" # prevent windows vm hanging on completion
    - CHANGELOG="$(git log --format='%h %s (@%an, %cr)' --tags --date-order $TRAVIS_COMMIT_RANGE)"
    - secure: "pTFgiKw9eMjcxRB0qHG/v1MMdPxZfOQkGM6b9UT5O0q95C3T0w3IEVJjs8I6hSwkQLn3USzocb265tSfjprSYfcVVm5oJnNFv+U6xCCwSvjTc8RNwO5gDRN0zfImU6XeRnT+Mi+LMwaT3vF8+jQhkRcyVY8aH0934DimPcB0KqnRXcRVaPNmEa2Sy3Z7uJaOJoFM5MRrMcz23S4HoI+Izyaq5hLdprcHpMlCI0nNiGWufds4rJqEUxyu7Lu6xdk8e8mtnQHUcpw2/pfZhb+7//674AxdJ1nhUQdclFwXC0n1xG5+B9cSM6qNq08TP0lIb9/FpgaCLV/VzTnB9rJzPJApSM7JCjsyjvHRGU3AonWKZ6lEjoD2P5QAu0EN6tZVptgtQ2iYFKLyxLNxpxn3dzju8DPX1W8w6FbHsC+CJyl/DvXAJVspEo8ta81mkzVMSvRhlyrJTdQJrvUhHTCOk9G/8fBU8nTjHqjd4iKG/G6qRRTnzx2PPpYx/H38ggJuQe5LZMyxvQBbO4uhOBUtrBtYquC6LeiHoV2J8FoBvSGnpYzPsS1oL8UKGzbhDjDfspeD2Hro+mbnbKamLF8AP4R7nv7lCxtdVQjDYHrfct5HmT1hRuEBrSTDIr1iFUOQP9jKXXMsLbpudeC0YRjwRC90ymWyQNgKzPl7eXdzPeA="

addons:
  chrome: stable
  apt:
    update: true

git:
  depth: 10 # quick clone
  quiet: true # save on logfiles

node_js:
  - 10 # version

before_install:
  # install 'rpm' on linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install rpm; fi
  # install 'nsis' on windows
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install nsis; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export PATH="/c/Program Files (x86)/NSIS:$PATH"; fi
  # install 'python' on all platforms supported
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install python3 python3-pip; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="$HOME/.local/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="$HOME/Library/Python/3.8/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install python --version 3.8.0; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export PATH="/c/Python38:/c/Python38/Scripts:/c/Users/travis/AppData/Roaming/Python/Python38/Scripts:$PATH"; fi

#install:
#  - pip3 -q install --user --upgrade j2cli # install pip

script:
  - echo "${CHANGELOG}" > CHANGELOG.md
  - cat CHANGELOG.md
  - ./.travis/build.sh

cache:
  pip: true
  yarn: true
  directories:
  - cache
  - '/c/Users/travis/AppData/Local/Temp/chocolatey'

deploy:
  - provider: releases
#    edge: true
    api_key:
      secure: "bLcQLlZSKejWvliUCfdcqZvFoXZ1f0dsBMzEsFw1s3w98fpC9SHiINtiGeO60y7vQktPQ/19cGg1yFvlG1AIKxYlPIbsPWHcqfVDPZiPAlIpBn+URPkeQjK55E9+iJPdeS+ao4svvgdZMO4ebYy3IjdH6/lx7revXJv1qWc8xvD8HYY1QrTUjweyeurVUxk4DxWoo7JjcJ8QIP9eVKJwyNjD8e9CcNfDfcdNJ/2DflzRNixPRJbI8Osy/aAWLHRMD9/dRjNSiegHrdenC+PQyZPjIcKfStWPF0nq63Wx/uhanwXBeHm0Cit44eKlEedGF64m6tePR9NGzl1Rg7sK+eTo1YDXwG9l0iPyjjQmGjZNKBpg1ZrruLSEonOMfdUPn/6nFUSTo0YBCUSuQ7ihR/1julnibkxNLIIERTdQr99V7iSuLPyGCSrkJk0I36w1HTjMlwPpw8u6zmVTUv/y2EqC/qxa5/9aSLKpRtK/Qz3AHKOAxRrQAerevDB4ngYjYmgXBQj8gSDa6G92jzfPEX0x9U4n6CozRx6GA3JBb111idKOlxFupP/9zx38SfyPKHjT/JiItU84tDftVTtEZrEKFQz7dIn99rCEI0ITgwCjiiqMtQ14qUExILUKrIYwcppwVdmPBQP6e+LD3BSMwKFCHyA0Cl2TQFxQ+a2HII8="
    #token: "${GITHUB_TOKEN}"
    #name: "${TRAVIS_TAG}"
    #body: "${CHANGELOG}"
    #tag_name: "${TRAVIS_TAG}"
    #target_commitish: "${TRAVIS_COMMIT}"
    file_glob: true
    file:
      - release/*
    cleanup: false # do not delete what has just been built
    draft: true
    prerelease: true
    overwrite: true
    #on:
    #  tags: true

after_success:
  - ./.travis/push.sh  #push to travisBuild repo
